class_name BijectionLevel1
extends BijectionLevel

func _init() -> void:
	super(
		"Subsets",
		"Binary Strings",
		"Subsets of {1, 2, ..., n}",
		"Binary strings of length n",
		{
			0: Bijection.new(
				0,
				# Left elements
				[
					BijectionElement.new("{}", true, 1), 
				],
				# Right elements 
				[
					BijectionElement.new("", false, 1),
				]
			),
			1: Bijection.new(
				1,
				# Left elements
				[
					BijectionElement.new("{}", true, 1), 
					BijectionElement.new("{1}", true, 2),
				],
				# Right elements 
				[
					BijectionElement.new("0", false, 1),
					BijectionElement.new("1", false, 2),
				]
			),
			2: Bijection.new(
				2,
				# Left elements
				[
					BijectionElement.new("{}", true, 1), 
					BijectionElement.new("{1}", true, 2),
					BijectionElement.new("{2}", true, 3),
					BijectionElement.new("{1, 2}", true, 4),
				],
				# Right elements 
				[
					BijectionElement.new("00", false, 1),
					BijectionElement.new("10", false, 2),
					BijectionElement.new("01", false, 3),
					BijectionElement.new("11", false, 4),
				]
			),
			3: Bijection.new(
				3,
				# Left elements
				[
					BijectionElement.new("{}", true, 1), 
					BijectionElement.new("{1}", true, 2),
					BijectionElement.new("{2}", true, 3),
					BijectionElement.new("{1, 2}", true, 4),
					BijectionElement.new("{3}", true, 5), 
					BijectionElement.new("{1, 3}", true, 6),
					BijectionElement.new("{2, 3}", true, 7),
					BijectionElement.new("{1, 2, 3}", true, 8),
				],
				# Right elements 
				[
					BijectionElement.new("000", false, 1),
					BijectionElement.new("100", false, 2),
					BijectionElement.new("010", false, 3),
					BijectionElement.new("110", false, 4),
					BijectionElement.new("001", false, 5),
					BijectionElement.new("101", false, 6),
					BijectionElement.new("011", false, 7),
					BijectionElement.new("111", false, 8)
				]
			),
			# n = 4, generated by ChatGPT
			4: Bijection.new(
				4,
				# Left elements
				[
					BijectionElement.new("{}", true, 1), 
					BijectionElement.new("{1}", true, 2),
					BijectionElement.new("{2}", true, 3),
					BijectionElement.new("{1, 2}", true, 4),
					BijectionElement.new("{3}", true, 5), 
					BijectionElement.new("{1, 3}", true, 6),
					BijectionElement.new("{2, 3}", true, 7),
					BijectionElement.new("{1, 2, 3}", true, 8),
					BijectionElement.new("{4}", true, 9),
					BijectionElement.new("{1, 4}", true, 10),
					BijectionElement.new("{2, 4}", true, 11),
					BijectionElement.new("{1, 2, 4}", true, 12),
					BijectionElement.new("{3, 4}", true, 13),
					BijectionElement.new("{1, 3, 4}", true, 14),
					BijectionElement.new("{2, 3, 4}", true, 15),
					BijectionElement.new("{1, 2, 3, 4}", true, 16),
				],
				# Right elements 
				[
					BijectionElement.new("0000", false, 1),
					BijectionElement.new("1000", false, 2),
					BijectionElement.new("0100", false, 3),
					BijectionElement.new("1100", false, 4),
					BijectionElement.new("0010", false, 5),
					BijectionElement.new("1010", false, 6),
					BijectionElement.new("0110", false, 7),
					BijectionElement.new("1110", false, 8),
					BijectionElement.new("0001", false, 9),
					BijectionElement.new("1001", false, 10),
					BijectionElement.new("0101", false, 11),
					BijectionElement.new("1101", false, 12),
					BijectionElement.new("0011", false, 13),
					BijectionElement.new("1011", false, 14),
					BijectionElement.new("0111", false, 15),
					BijectionElement.new("1111", false, 16)
				]
			),
	})
	
