extends BijectionDefinition
class_name DefinitionBalancedParentheses


func _init() -> void:
	super(
		"Balanced Parentheses",
		"A sequence of parentheses is balanced if it is generated by the grammar with production rule S -> (S) | epsilon."
	)
